apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: smseagle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smseagle
        environment: dev
    spec:
      containers:
      - name: smseagle
        image: redcrossredcrescent/smseagle:1
        ports:
        - containerPort: 80
          name: incoming
