kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kafka
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: kafka
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: zookeeper


      